### ISSUE TITLE
Is this effort still alive?

### ISSUE THREAD

**Issue by DevQps** [disclose/dnssecuritytxt#10]
# Is this effort still alive? 
Since there has not been any contributions for quite a while (for as far as I can see). I was wondering if this effort was still alive.
Security.txt because an official RFC some time ago (https://www.rfc-editor.org/rfc/rfc9116) but it requires the use of a webserver which can be perceived as overhead in some cases.

It would be great if we could push this effort forward to an official RFC which complements security.txt in the world of vulnerability notification. I would be willing to help write the RFC, but I would first like to sync with you guys about the work you have already done in this area.

**Comment by yosignals** [comment]
Hey @DevQps Yes! it's still active - apologies for the delay, we have some conversations around what the rfc looks like, and the value - I think the biggest hurdle is to articulate the nuances between the two efforts, @caseyjohnellis @DevQps do we want to get our heads together ?

**Comment by DevQps** [comment]
@yosignals That would be great! Let me know what would be the best way to contact the both of you.

**Comment by yosignals** [comment]
Let's get started next week @DevQps I think Casey is maxed out  of late, I'm away until Monday, after that let's get cracking ? Maybe you and me can jump on a call and rattle out what we think and build on that

**Comment by DevQps** [comment]
@yosignals That's a great idea! Feel free to let me know how I should contact you, but I am open for a call to discuss this.

**Comment by yosignals** [comment]
> @yosignals That's a great idea! Feel free to let me know how I should contact you, but I am open for a call to discuss this.

If you're around sometime this weekend and have discord I'm 'n0x00#2977' ping me and we can get crackin ! Thank you, this is gonna be awesome 🙌

**Comment by DevQps** [comment]
That is fine! I have sent you a friend request (JohnDoe). I am available on Saturday morning and afternoon, but let's discuss the details on Discord.
