### ISSUE TITLE
Suggestion: Allow for linking to `security.txt` (or other external resources) specifying a checksum

### ISSUE THREAD

**Issue by m-ueberall** [disclose/dnssecuritytxt#7]
For sites which already maintain a `security.txt` file (see [A File Format to Aid in Security Vulnerability Disclosure](https://datatracker.ietf.org/doc/draft-foudil-securitytxt/)) which also allows specifying preferred languages and encryption keys, it might not make sense to maintain DNS TXT records unless they simply link to `https://example.org/.well-known/security.txt`.

As [pointed out](https://twitter.com/DnsSecuritytxt/status/1382973567449518082), _the obvious challenge_ [on the other hand] _is that it inserts the owner of the web host between the user and the contact channel and policy details._ This is true for all external references by means of a URL, of course.

DNS entries can be secured with cryptographic signatures (see [DNS Security Introduction and Requirements](https://datatracker.ietf.org/doc/rfc4033/)), but a simple URL specified above—regardless of what it refers to—only specifies the location, but does not provide a means to validate the contents without the aid of _additional_ roots of trust. While the latter _should_ be used if available, an additional _checksum_ provided as part of the DNS entries could at least be used as "last resort" (or rather, to utilize DNSSEC _to its full extent_ w.r.t. this use case).

**Comment by yosignals** [comment]
Hey! Thanks, That's an interesting idea, I think this will be something that can be cited in the _security. record set, while the main principle is to provide a point of contact, we've had conversations about the freedom of _security. personally, I like the minimal approach of having a point of contact, a privacy method if desired (PGP etc...) , and a link to the security page, but there is no reason why someone couldn't add their security.txt file(s) if they wanted to maintain managing them on a host by host / site by site orchestration, it may be easier to stick to DNS as an authoritative route to security contacts but, _security. is a good place to demonstrate what you want people to know, it might be nice to see how people format those and hope that it follows suite with the general schema

**Comment by yosignals** [comment]
OK Closing this, but to reiterate...

the principle here is to provide means for contact, in the APEX TXT record, and an optional _security. space for similar and relative security information, there is list in the APEX, it just delivers in it's simplest terms: security contact information.

but with the _security. record there is freedom to define what you want, if you wanted to inherit some of security.txt's very granular options, have at it, I think we (@yesnet0 citation needed) would prefer that entries follow a machine parsable and human readable schema such as:

`purpose_title= information1; information2;more if needed;etc;` (max 255 chars)

We want people to use DNSSEC and where possible we will nudge people to using it, it's not for us to enforce, I agree, it's certainly better than not having it. what we dont want to do is set a huge architectural requirement for some contact information, if they dont have it, i'm sure they hear about it in every security report, and hopefully that will chip away to the point where action is taken, but it's out of our hands, if they do have it, great, get signing!  maybe we'll put some examples up too for good measure. 

With reguards to content validation we agree, but think about what we are offering here, it's first and formost, contact information to allow access to the security department, by email and an optional link to a URL, the argument for content valudation is fair, and more reason why not to use security.txt if you care that much as that too is content. but if we focus on fighting the mean and not the edge, providing a URL to a security page moves into the risk acceptance criteria of - if someone is in a position to modify the DNS record or secuirty page , why dont they just (xyz). 
sure we could wax lyrical about how to monitor for DNS changes, or how to use DNSSEC but those are out of scope, we will assume that you're doing things the way you want to do things less good or more good. it's a fight worth having but not from us. 

We are in early days with this project, but it's good to know that the potential challenge being presented are not show stoppers and that the simplicity of the idea wont get burried in technicalities or nuanced situations. we would hope that everyone operates their DNS admin to a highly competent security focused manner but often that isnt the case, and as a least case, having contact information available is our job done, if someone wants to validate that poor DNS quality may effect the records integrity, i'd agree with them and equally defer them to the organisation as the records themselves are not the posture or configuration, we can only desire best practices often there are various reasons why that cannot be the case, either way, I think we agree good security practice is good security practice, but we simply offer an idea with a proposed way to organise the idea to make it more useful. - Thanks again !
